spring:
  application:
    name: SpringBoot-Just-Auth
  datasource:
    url: jdbc:mysql://localhost:3306/db7?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080

oauth:
  github:
    redirect-uri: http://127.0.0.1:8080/oauth/callback/github
    client-secret: 
    client-id: 
